# Generated by Django 3.0.2 on 2020-01-17 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='vot',
            new_name='votes',
        ),
    ]
